name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.15.0" # Match your local Node.js version

      - name: Install dependencies
        run: npm ci # Ensures a clean install of dependencies

      - name: Verify Jest Installation
        run: npx jest --version # Confirm Jest is installed before running tests

      - name: Run tests
        run: npx jest # Use npx to run Jest, avoiding permission issues
