name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.15.0" # Your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Ensure Jest is executable
        run: chmod +x node_modules/.bin/jest # Fix permission issue

      - name: Run tests
        run: npx jest # Use 'npx jest' to avoid permission issues
