name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.15.0" # Updated to your current Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
